-- =====================================================================
-- SINCRONIZACIÓN DEL CATÁLOGO WEB CON catalogo-artesana.pptx
-- Ejecutar en Supabase SQL Editor después de supabase_setup.sql.
-- Actualiza textos, precios e imágenes sin modificar el stock existente.
-- =====================================================================

WITH pptx_products AS (
  SELECT * FROM (VALUES
    ('Jabón de Arroz','Luminosidad natural','/catalog/jabon-arroz.png','90 g',35.0,'Para una piel más suave, uniforme y luminosa dentro de una rutina constante.','Empareja la textura cutánea. Remueve impurezas dejando la piel tersa, profundamente suave y renovada.','Barra dermocosmética de limpieza formulada artesanalmente con extracto nativo de arroz.','Frotar la barra con las manos húmedas hasta obtener espuma, masajear la zona con movimientos circulares durante unos segundos y enjuagar con abundante agua.','Combo sugerido: Jabón de Arroz + Crema Facial. Ideal para rutina en las mañanas: elimina toxinas nocturnas y prepara la piel para recibir hidratación.','Ideal para pieles opacas, con falta de brillo, manchas y tono irregular.','rosa',14),
    ('Jabón de Aloe Vera','Humectación diaria','/catalog/jabon-aloe-vera.png','90 g',35.0,'Una barra suave para acompañar la hidratación y el cuidado cotidiano de la piel.','Estimula la regeneración celular y repara microlesiones cutáneas. Calma irritaciones, desinflama y devuelve la elasticidad.','Elaborada con gel concentrado de aloe vera. Limpieza extrasuave que ayuda a restaurar la hidratación celular y sanar tejidos de la piel.','Frotar la barra con las manos húmedas hasta obtener espuma, masajear la zona con movimientos circulares durante unos segundos y enjuagar con abundante agua.','Es el aliado perfecto para recuperar la piel después de la exposición solar o el afeitado. Incorpórelo en su rutina diaria para tener un rostro fresco y protegido.','Es el jabón más noble, ideal para todo tipo de piel.','verde',20),
    ('Jabón de Azufre','Control de brillo','/catalog/jabon-azufre.png','90 g',35.0,'Limpieza específica para piel grasa, brillo persistente y poros congestionados.','Ofrece una potente acción seborreguladora y antiséptica que combate eficazmente la bacteria responsable del acné. Previene puntos negros.','El azufre se usa en cosmética por su apoyo en higiene de piel grasa, limpieza de poros obstruidos y control del brillo.','Frotar la barra con las manos húmedas hasta obtener espuma, masajear la zona T con movimientos circulares durante unos segundos y enjuagar con abundante agua.','Incorpórelo inicialmente de 2 a 3 veces por semana en la rutina nocturna. Al notar reducción de grasa, espaciar su uso para evitar resecar la piel.','Uso exclusivo por las noches, sin exposición al sol, al viento ni al maquillaje.','terracota',6),
    ('Jabón de Manzanilla','Piel sensible','/catalog/jabon-manzanilla.png','90 g',30.0,'Suavidad herbal para limpiar, nutrir y dar confort a pieles delicadas.','Su alto contenido de azuleno y bisabolol aporta una potente acción desinflamatoria que calma irritaciones y rojeces.','La manzanilla aporta compuestos calmantes asociados al confort de la piel sensible sin generar tirantez ni resequedad.','Frotar la barra con las manos húmedas hasta obtener espuma, masajear la zona con movimientos circulares durante unos segundos y enjuagar con abundante agua.','Es el aliado para relajar el cutis al final del día. Incorporar en la rutina nocturna para liberar la piel del estrés ambiental acumulado.','Fórmula artesanal para un tratamiento calmante por excelencia.','rosa',12),
    ('Jabón de Romero','Herbal revitalizante','/catalog/jabon-romero.png','90 g',30.0,'Limpieza estimulante con aroma herbal para una piel fresca y tonificada.','Aporta una potente acción antioxidante que protege el colágeno natural. Minimiza poros dilatados y reafirma los tejidos.','El romero contiene antioxidantes naturales usados en cuidado cutáneo.','Frotar la barra con las manos húmedas hasta obtener espuma, masajear la zona con movimientos circulares, dejar que los activos botánicos actúen y enjuagar con abundante agua.','Incorpórelo en su rutina de baño matutina; su aroma herbal alivia la fatiga mental, aclara las ideas y recarga energía para iniciar el día con frescura.','Ideal para pieles mixtas a grasas y zonas que requieren activación circulatoria.','terracota',8),
    ('Jabón de Carbón','Jabones artesanales','/catalog/jabon-carbon.png','90 g',30.0,'Limpieza profunda para piel con exceso de grasa, brillo e impurezas visibles.','Funciona como imán que atrae y remueve toxinas, metales pesados y residuos de contaminación urbana. Limpia poros a profundidad, elimina exceso de sebo y oxigena capas cutáneas.','El carbón activado ayuda a adsorber sebo, partículas e impurezas superficiales.','Frotar la barra con las manos húmedas hasta obtener espuma, masajear la zona con movimientos circulares, dejar que los activos botánicos actúen y enjuagar con abundante agua.','Incorporar de 2 a 3 veces por semana en la rutina nocturna.','Ideal para pieles urbanas, mixtas, grasas o con tendencia a puntos negros.','verde',15),
    ('Jabón de Bicarbonato','Jabón artesanal','/catalog/jabon-bicarbonato.png','90 g',30.0,'Limpieza purificante y curativa que actúa como micro exfoliante natural sin componentes sintéticos agresivos.','Piel: elimina células muertas, controla exceso de grasa y combate el acné. Cabello: limpia el cuero cabelludo y ayuda a reducir la caspa.','Jabón artesanal y orgánico de limpieza profunda. Actúa como micro exfoliante natural que purifica la piel sin químicos agresivos.','Rostro y cuerpo: generar espuma, aplicar con masajes circulares suaves y enjuagar. Cabello: aplicar sobre cuero cabelludo húmedo, masajear la raíz y enjuagar.','Uso ideal de 2 a 3 veces por semana en pieles mixtas a grasas. Hidratar la piel después de su uso.','Evitar en pieles muy secas, sensibles o irritadas.','terracota',10),
    ('Crema Anti-Stress','Cuidado corporal','/catalog/crema-anti-stress.png','150 g',99.0,'Fórmula relajante con magnesio y aceites esenciales para masaje localizado.','Actúa sobre fibras musculares tensas, disminuyendo niveles corporales de cortisol. Alivia contracturas de cuello, espalda y hombros.','Emulsión corporal terapéutica de rápida absorción para aliviar fatiga neuromuscular y promover relajación muscular profunda.','Dosificar una cantidad generosa y aplicar con masaje firme y pausado en zonas de tensión como nuca, hombros, espalda o planta de los pies hasta absorción completa.','Utilícela después de una ducha tibia antes de acostarse. En caso de migraña, masajear con poco producto a nivel de la sien.','Ideal para aromaterapia: colocar un poco en la palma, frotar y respirar profundo.','rosa',10),
    ('Crema Vital-Flex','Alivio corporal rápido','/catalog/crema-vital-flex.png','150 g',99.0,'Crema para masaje en zonas de tensión con sensación de calor intenso.','Acción analgésica y antiinflamatoria natural que alivia tensiones, rigidez y molestias articulares. Su efecto calor mejora flexibilidad y recuperación post-esfuerzo.','Emulsión terapéutica de acción térmica con extractos puros de árnica y copaiba. Estimula microcirculación local y prepara la estructura muscular para esfuerzo físico.','Dosificar la cantidad necesaria y aplicar con masaje vigoroso y circular en áreas que requieran activación o alivio hasta absorción.','Aplicar de 15 a 20 minutos antes de entrenar para prevenir tirones, optimizar elasticidad y disipar fatiga en articulaciones.','Altamente recomendado para deportistas y personas físicamente activas en su día a día.','terracota',8),
    ('Crema Facial','Hidratación nutritiva','/catalog/crema-facial.png','50 g',39.0,'Sábila, colágeno, pepino y vitaminas A, E y C para piel nutrida y flexible.','Efecto reafirmante y antioxidante que combate signos de envejecimiento prematuro. Reduce líneas de expresión y restaura luminosidad natural.','Crema regeneradora con colágeno soluble, ácido láctico y extractos botánicos puros. Diseñada para fundirse con la piel y aportar hidratación profunda.','Aplicar una pequeña cantidad con movimientos ascendentes y suaves desde el centro hacia afuera en rostro, cuello y escote.','Usar en mañanas y noches. Por sus propiedades de pepino y aloe, desinflama y refresca dejando la piel tersa y protegida.','Ideal para pieles maduras, secas, opacas o con pérdida de elasticidad.','verde',10),
    ('Shampoo Anti-Stress','Cuidado capilar','/catalog/shampoo-anti-stress.png','160 g',99.0,'Refrescante y relajante, con aceites esenciales y extractos botánicos.','Triple acción terapéutica: estimula microcirculación para frenar caída, fortalece el folículo desde la raíz y regula exceso de grasitud.','Tratamiento capilar libre de sal y parabenos, enriquecido con extractos de ortiga, romero, menta y lavanda.','Aplicar sobre el cuero cabelludo, masajear suavemente con las yemas durante 2 a 3 minutos y enjuagar con abundante agua.','Utilizar diariamente o de 3 a 4 veces por semana. Sus aromas herbales y efecto frío ayudan a disipar el cansancio mental.','Producto unisex que aporta frescura, alivia tensión acumulada y devuelve brillo natural.','verde',15),
    ('Kéfir de Leche','Probiótico artesanal','/catalog/kefir-leche.png','1 L / 1/2 L',40.0,'Bebida probiótica artesanal de consumo diario para hábitos de bienestar.','Restaura y fortalece la microbiota intestinal gracias a bacterias benéficas y levaduras. Mejora digestión, reduce inflamación abdominal y potencia el sistema inmunológico.','Alimento lácteo fermentado vivo y artesanal obtenido mediante nódulos de kéfir en leche entera. Superalimento natural libre de conservantes.','Iniciar con 5 ml al día en ayunas e incrementar progresivamente hasta llegar a consumir un vaso diario.','Mantener refrigerado y consumir dentro del periodo de vida útil. Puede consumirse solo, con miel o en batidos de frutas y cereales.','Vida útil de 15 días desde elaboración. Se prepara únicamente a pedido con 1 día de anticipación. Precio: Bs 40 el litro / Bs 25 medio litro.','rosa',25)
  ) AS v(name, category, image_url, presentation, price, intro, benefit, use, apply, recommend, note, accent, stock)
), updated AS (
  UPDATE public.products p
  SET
    category = v.category,
    image_url = v.image_url,
    presentation = v.presentation,
    price = v.price,
    intro = v.intro,
    benefit = v.benefit,
    use = v.use,
    apply = v.apply,
    recommend = v.recommend,
    note = v.note,
    accent = v.accent,
    is_active = true
  FROM pptx_products v
  WHERE translate(lower(p.name), 'áéíóúüÁÉÍÓÚÜ', 'aeiouuAEIOUU') = translate(lower(v.name), 'áéíóúüÁÉÍÓÚÜ', 'aeiouuAEIOUU')
  RETURNING p.name
)
INSERT INTO public.products (name, category, image_url, presentation, price, stock, intro, benefit, use, apply, recommend, note, accent, is_active)
SELECT v.name, v.category, v.image_url, v.presentation, v.price, v.stock, v.intro, v.benefit, v.use, v.apply, v.recommend, v.note, v.accent, true
FROM pptx_products v
WHERE NOT EXISTS (
  SELECT 1 FROM public.products p WHERE translate(lower(p.name), 'áéíóúüÁÉÍÓÚÜ', 'aeiouuAEIOUU') = translate(lower(v.name), 'áéíóúüÁÉÍÓÚÜ', 'aeiouuAEIOUU')
);
